### Cast a vote
POST http://localhost:3000/api/votes
Content-Type: application/json

{
  "poll_id": 12,
  "option_id": 7,
  "user_id": "83ecfc4f-bb38-48c4-899b-5521eb12fc99"
}

### Get votes for a poll
GET http://localhost:3000/api/polls/12/votes

### Delete a vote
DELETE http://localhost:3000/api/votes/1
Content-Type: application/json

{
  "user_id": "83ecfc4f-bb38-48c4-899b-5521eb12fc99"
}